// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoj2ZDM4qoNsF-wYZl6_ydc9emrkDnhK0',
    appId: '1:1083990323056:web:513018a23671a37b00e9b5',
    messagingSenderId: '1083990323056',
    projectId: 'cuutrobaolu',
    authDomain: 'cuutrobaolu.firebaseapp.com',
    storageBucket: 'cuutrobaolu.firebasestorage.app',
    measurementId: 'G-HC4DK8JR20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCViz-gByp9AzU89kU2dFJBEulQptlBfHo',
    appId: '1:1083990323056:android:c704229acaa32a5b00e9b5',
    messagingSenderId: '1083990323056',
    projectId: 'cuutrobaolu',
    storageBucket: 'cuutrobaolu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC1HQnoMolQcfU2BUUiJE1gU_yugTrVrQ',
    appId: '1:1083990323056:ios:2e2a16b09ad6cbfd00e9b5',
    messagingSenderId: '1083990323056',
    projectId: 'cuutrobaolu',
    storageBucket: 'cuutrobaolu.firebasestorage.app',
    iosBundleId: 'com.example.cuutrobaolu',
  );
}
