// Mocks generated by Mockito 5.4.6 from annotations
// in cuutrobaolu/test/data/services/hybrid_alert_scoring_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cuutrobaolu/data/services/ai_service_client.dart' as _i4;
import 'package:cuutrobaolu/domain/entities/alert_entity.dart' as _i5;
import 'package:cuutrobaolu/domain/entities/scored_alert_entity.dart' as _i2;
import 'package:cuutrobaolu/domain/services/alert_scoring_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeScoredAlert_0 extends _i1.SmartFake implements _i2.ScoredAlert {
  _FakeScoredAlert_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlertScoringService_1 extends _i1.SmartFake
    implements _i3.AlertScoringService {
  _FakeAlertScoringService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAIScoreResult_2 extends _i1.SmartFake implements _i4.AIScoreResult {
  _FakeAIScoreResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuplicateCheckResult_3 extends _i1.SmartFake
    implements _i4.DuplicateCheckResult {
  _FakeDuplicateCheckResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationTimingResult_4 extends _i1.SmartFake
    implements _i4.NotificationTimingResult {
  _FakeNotificationTimingResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AlertScoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertScoringService extends _i1.Mock
    implements _i3.AlertScoringService {
  MockAlertScoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get weightSeverity =>
      (super.noSuchMethod(Invocation.getter(#weightSeverity), returnValue: 0.0)
          as double);

  @override
  double get weightType =>
      (super.noSuchMethod(Invocation.getter(#weightType), returnValue: 0.0)
          as double);

  @override
  double get weightTimeDecay =>
      (super.noSuchMethod(Invocation.getter(#weightTimeDecay), returnValue: 0.0)
          as double);

  @override
  double get weightDistance =>
      (super.noSuchMethod(Invocation.getter(#weightDistance), returnValue: 0.0)
          as double);

  @override
  double get weightAudience =>
      (super.noSuchMethod(Invocation.getter(#weightAudience), returnValue: 0.0)
          as double);

  @override
  double get timeDecayLambda =>
      (super.noSuchMethod(Invocation.getter(#timeDecayLambda), returnValue: 0.0)
          as double);

  @override
  double get maxDistanceRadius =>
      (super.noSuchMethod(
            Invocation.getter(#maxDistanceRadius),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculatePriorityScore({
    required _i5.AlertEntity? alert,
    required double? userLat,
    required double? userLng,
    required String? userRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculatePriorityScore, [], {
              #alert: alert,
              #userLat: userLat,
              #userLng: userLng,
              #userRole: userRole,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  _i2.ScoredAlert calculateScoredAlert({
    required _i5.AlertEntity? alert,
    required double? userLat,
    required double? userLng,
    required String? userRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateScoredAlert, [], {
              #alert: alert,
              #userLat: userLat,
              #userLng: userLng,
              #userRole: userRole,
            }),
            returnValue: _FakeScoredAlert_0(
              this,
              Invocation.method(#calculateScoredAlert, [], {
                #alert: alert,
                #userLat: userLat,
                #userLng: userLng,
                #userRole: userRole,
              }),
            ),
          )
          as _i2.ScoredAlert);

  @override
  List<_i2.ScoredAlert> calculateMultipleScores({
    required List<_i5.AlertEntity>? alerts,
    required double? userLat,
    required double? userLng,
    required String? userRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateMultipleScores, [], {
              #alerts: alerts,
              #userLat: userLat,
              #userLng: userLng,
              #userRole: userRole,
            }),
            returnValue: <_i2.ScoredAlert>[],
          )
          as List<_i2.ScoredAlert>);

  @override
  _i3.AlertScoringService copyWith({
    double? weightSeverity,
    double? weightType,
    double? weightTimeDecay,
    double? weightDistance,
    double? weightAudience,
    double? timeDecayLambda,
    double? maxDistanceRadius,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #weightSeverity: weightSeverity,
              #weightType: weightType,
              #weightTimeDecay: weightTimeDecay,
              #weightDistance: weightDistance,
              #weightAudience: weightAudience,
              #timeDecayLambda: timeDecayLambda,
              #maxDistanceRadius: maxDistanceRadius,
            }),
            returnValue: _FakeAlertScoringService_1(
              this,
              Invocation.method(#copyWith, [], {
                #weightSeverity: weightSeverity,
                #weightType: weightType,
                #weightTimeDecay: weightTimeDecay,
                #weightDistance: weightDistance,
                #weightAudience: weightAudience,
                #timeDecayLambda: timeDecayLambda,
                #maxDistanceRadius: maxDistanceRadius,
              }),
            ),
          )
          as _i3.AlertScoringService);

  @override
  bool isWeightValid() =>
      (super.noSuchMethod(
            Invocation.method(#isWeightValid, []),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [AIServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIServiceClient extends _i1.Mock implements _i4.AIServiceClient {
  MockAIServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i7.Future<_i4.AIScoreResult> getAlertScore(
    _i5.AlertEntity? alert, {
    required double? userLat,
    required double? userLng,
    required String? userRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAlertScore,
              [alert],
              {#userLat: userLat, #userLng: userLng, #userRole: userRole},
            ),
            returnValue: _i7.Future<_i4.AIScoreResult>.value(
              _FakeAIScoreResult_2(
                this,
                Invocation.method(
                  #getAlertScore,
                  [alert],
                  {#userLat: userLat, #userLng: userLng, #userRole: userRole},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.AIScoreResult>);

  @override
  _i7.Future<_i4.DuplicateCheckResult> checkDuplicate(
    _i5.AlertEntity? newAlert,
    List<_i5.AlertEntity>? existingAlerts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkDuplicate, [newAlert, existingAlerts]),
            returnValue: _i7.Future<_i4.DuplicateCheckResult>.value(
              _FakeDuplicateCheckResult_3(
                this,
                Invocation.method(#checkDuplicate, [newAlert, existingAlerts]),
              ),
            ),
          )
          as _i7.Future<_i4.DuplicateCheckResult>);

  @override
  _i7.Future<_i4.NotificationTimingResult> getNotificationTiming({
    required String? alertSeverity,
    required String? userId,
    Map<String, dynamic>? userContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationTiming, [], {
              #alertSeverity: alertSeverity,
              #userId: userId,
              #userContext: userContext,
            }),
            returnValue: _i7.Future<_i4.NotificationTimingResult>.value(
              _FakeNotificationTimingResult_4(
                this,
                Invocation.method(#getNotificationTiming, [], {
                  #alertSeverity: alertSeverity,
                  #userId: userId,
                  #userContext: userContext,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.NotificationTimingResult>);

  @override
  _i7.Future<void> logEngagement({
    required String? alertId,
    required String? userId,
    required String? action,
    int? timeSlot,
    double? actualScore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEngagement, [], {
              #alertId: alertId,
              #userId: userId,
              #action: action,
              #timeSlot: timeSlot,
              #actualScore: actualScore,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getEngagementStats({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#getEngagementStats, [], {#days: days}),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getDuplicateStats({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#getDuplicateStats, [], {#days: days}),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getTimingStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTimingStats, []),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
